---
title: 'spot check single cell GEO records'
date: '`r Sys.Date()`'
# package: scmetadata
author:
  - name: Rui Fu
    affiliation: RNA Bioscience Initative, University of Colorado School of Medicine
output:
  BiocStyle::html_document:
    toc_float: true

vignette: >
    %\VignetteIndexEntry{Introduction to clustifyr}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}  
---

```{r "knitr options", echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  fig.align = "center",
  comment = "#>",
  crop = NULL
)
```

```{r load}
library(here)
library(tidyverse)
gds <- readRDS(here("inst", "extdata", paste0("geo_", "091020", ".rds")))
fp <- read_tsv(here("inst", "extdata", "falsepos.txt"), col_names = F) %>% pull(1)
gds <- gds %>% mutate(usable = ifelse(id %in% fp, "no", usable))
```

```{r sample_kent}
dplyr_vec <- function(a, b) {
  c(a, b)
}
set.seed(42)
gds %>% sample_n(100) %>% select(c(id, suppfiles, tarfiles, usable)) %>% 
  mutate(files = map2(suppfiles, tarfiles, dplyr_vec)) %>% 
  select(-c(suppfiles, tarfiles)) %>% 
  unnest(files) %>% 
  group_by(id) %>% 
  mutate(link = ifelse(row_number() == 1, 
                       str_c('<a href="','https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', id, '">GEO</a>'),
                       NA)) %>% 
  DT::datatable(escape = FALSE)

set.seed(42)
gds %>% sample_n(100) %>% select(c(id, usable)) %>% 
  mutate(link = str_c('https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', id)) %>% write_tsv("check100_kent.tsv")
```

```{r sample_rui}
dplyr_vec <- function(a, b) {
  c(a, b)
}
set.seed(34)
gds %>% sample_n(100) %>% select(c(id, suppfiles, tarfiles, usable)) %>% 
  mutate(files = map2(suppfiles, tarfiles, dplyr_vec)) %>% 
  select(-c(suppfiles, tarfiles)) %>% 
  unnest(files) %>% 
  group_by(id) %>% 
  mutate(link = ifelse(row_number() == 1, 
                       str_c('<a href="','https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', id, '">GEO</a>'),
                       NA)) %>% 
  DT::datatable(escape = FALSE)

set.seed(34)
gds %>% sample_n(100) %>% select(c(id, usable)) %>% 
  mutate(link = str_c('https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', id)) %>% write_tsv("check100_rui.tsv")
```