---
title: 'single cell GEO records'
date: '`r Sys.Date()`'
package: scmetadata
author:
  - name: Rui Fu
    affiliation: RNA Bioscience Initative, University of Colorado School of Medicine
output:
  BiocStyle::html_document:
    toc_float: true

vignette: >
    %\VignetteIndexEntry{Introduction to clustifyr}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}  
---

```{r "knitr options", echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  fig.align = "center",
  comment = "#>",
  crop = NULL
)
```

```{r}
library(here)
library(tidyverse)
date <- "090920"
```

## Parse GEO query
```{r}
source(here("utils", "geo_query.R"))
(gds_h$usable == "yes") %>% mean()
(gds_m$usable == "yes") %>% mean()
```

## Parse database from 
```{r}
library(googlesheets4)
gs4_deauth()
data <- read_sheet("https://docs.google.com/spreadsheets/d/1En7-UV0k0laDiIfjFkdn7dggyR7jIk3WH8QgXaMOZF0", sheet = "Data")
h_data <- data %>% filter(Measurement == "RNA-seq") %>% filter(str_detect(`Data location`, "^GSE")) %>% filter(str_detect(Organism, "Human"))
m_data <- data %>% filter(Measurement == "RNA-seq") %>% filter(str_detect(`Data location`, "^GSE")) %>% filter(str_detect(Organism, "Mouse"))
```

```{r}
h_ids <- h_data$`Data location` %>% strsplit(", ") %>% unlist()
length(intersect(gds_h$id, h_ids))/length(h_ids)

m_ids <- m_data$`Data location` %>% strsplit(", ") %>% unlist()
length(intersect(gds_m$id, m_ids))/length(m_ids)
```

```{r}
setdiff(h_ids, gds_h$id)
```
