---
title: "Re-analysis workflows"
author: "Kent Riemondy RBI"
date: "9/22/2020"
always_allow_html: true
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Workflows

```{r}
library(here)
library(DiagrammeR)
library(DiagrammeRsvg)
library(magrittr)
library(rsvg)
library(SingleCellExperiment)
library(Seurat)
library(scran)
library(scater)
library(igraph)
library(tidyverse)
```

```{r}
g_fn <- here("inst", "extdata", "workflow.gv")
grViz(g_fn)
```


Saving the diagram as a pdf took awhile to figure out. See https://github.com/rich-iannone/DiagrammeR/issues/70#issuecomment-179403772 


```{r}
inch_to_px <- function(x, dpi = 300) { x * dpi}

w_inch <- 4
asp_ratio = 1.6
w <-  inch_to_px(w_inch)
h <- inch_to_px(w_inch * asp_ratio)

grViz(g_fn, width = w, height = h ) %>% 
  export_svg %>% 
  charToRaw %>% 
  rsvg_pdf("workflow-graph.pdf")
```


# Required data

```{r}
ncells <- 200
u <- counts(mockSCE(ncells = ncells))

cell_ids <- map_chr(1:ncells, 
                    ~sample(c("A", "T", "C", "G"), 
                            16,
                            replace = TRUE) %>% 
                      str_c(collapse = ""))

colnames(u) <- cell_ids

sce <- SingleCellExperiment(assays=list(counts=u))

sce <- sce %>% 
  logNormCounts() %>% 
  runPCA() %>% 
  runUMAP()

colData(sce)$clusters <- buildSNNGraph(sce) %>% 
  cluster_fast_greedy(.) %>% 
  .$membership

colData(sce)$cell_type <- sample(c("B", "T", "NK", "Mac"), 
                                 ncol(sce),
                                 replace = TRUE)

colData(sce) <- colData(sce)[c("clusters", "cell_type")]

mdata <- as.data.frame(colData(sce))
umap <- reducedDim(sce, "UMAP")
colnames(umap) = c("UMAP_1", "UMAP_2")
```

## UMI count Matrix

```{r, echo = FALSE}
counts(sce)[1:5, 1:4]
```

## Cell-level metadata
```{r, echo = FALSE}
cbind(mdata, umap)[1:5, 1:4]
```
<br>

<br>
<br>



<br>

<br> 
\newpage


# Example metadata export code

## SCE

```{r}
mdata <- as.data.frame(colData(sce))
umap <- reducedDim(sce, "UMAP")
colnames(umap) <- c("UMAP_1", "UMAP_2")
mdata <- cbind(mdata, umap)
write.csv(mdata, file = "cell-level-mdata.csv")
```

## Seurat

```{r}
seurat_object <- pbmc_small 
mdata <- cbind(seurat_object@meta.data, Embeddings(seurat_object, "tsne"))
write.csv(mdata, file = "cell-level-mdata.csv")
```

## Scanpy


```{python, eval = FALSE}
import scanpy
import pandas
adata = scanpy.datasets.pbmc3k_processed()
mdata = adata.obs
umap = adata.obsm.to_df()[["X_umap1", "X_umap2"]]
pandas.concat([mdata, umap]).to_csv("cell-level-metadata.csv")
```
