on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '00 01 01 * *'

name: Query

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    timeout-minutes: 1200

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: nicholasmfraser/rbiorxiv, any::pkgdown, local::.
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        timeout-minutes: 1200
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit README
        run: |
          git add README.md man/figures/*
          git add inst/extdata/current_geo.rds
          git add inst/extdata/arrayexpress_sets_proc_add.tsv.gz
          git commit -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
